language: ruby

sudo: false

notifications:
  - false

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install: gem install bundler -v 1.16.1

script:
  - bundle exec rspec spec
  - bundle exec rubocop --require rubocop-rspec
